# Generated by Django 4.0 on 2022-05-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_name_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
