# Generated by Django 4.0 on 2022-04-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0006_message_target_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='auth.user'),
        ),
    ]
