# Generated by Django 4.0 on 2022-04-05 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_remove_message_target_remove_room_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='clients_subscribed',
        ),
        migrations.AddField(
            model_name='room',
            name='users_subscribed',
            field=models.ManyToManyField(related_name='users_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
